# largely taken from https://github.com/xgcm/xgcm/blob/master/.travis.yml

language: python
python:
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda config --add channels conda-forge
  - conda config --add channels nesii/label/dev-esmf
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION esmpy xarray numpy scipy pytest
  - source activate test-environment
  - pip install -e .

script:
  - pytest -v
